# UMLS Semantic Type TUI codes to Descriptions
# Source: UMLS Semantic Network (https://www.nlm.nih.gov/research/umls/SemanticTypes/semantic_types_table.html)

SEMANTIC_TYPE_MAP = {
    'T001': 'Organism',
    'T002': 'Plant',
    'T004': 'Fungus',
    'T005': 'Virus',
    'T007': 'Bacterium',
    'T008': 'Rickettsia or Chlamydia',
    'T010': 'Animal',
    'T011': 'Amphibian',
    'T012': 'Bird',
    'T013': 'Fish',
    'T014': 'Reptile',
    'T015': 'Mammal',
    'T016': 'Human',
    'T017': 'Anatomical Structure',
    'T018': 'Embryonic Structure',
    'T019': 'Congenital Abnormality',
    'T020': 'Acquired Abnormality',
    'T021': 'Body Part, Organ, or Organ Component',
    'T022': 'Body System',
    'T023': 'Body Region',
    'T024': 'Body Space or Junction',
    'T025': 'Body Location or Region',
    'T026': 'Body Substance',
    'T028': 'Cell',
    'T029': 'Cell Component',
    'T030': 'Gene or Genome',
    'T031': 'Fully Formed Anatomical Structure',
    'T032': 'Organism Attribute',
    'T033': 'Finding',
    'T034': 'Laboratory or Test Result',
    'T037': 'Injury or Poisoning',
    'T038': 'Biologic Function',
    'T039': 'Physiologic Function',
    'T040': 'Organism Function',
    'T041': 'Mental Process',
    'T042': 'Organ or Tissue Function',
    'T043': 'Cell Function',
    'T044': 'Molecular Function',
    'T045': 'Genetic Function',
    'T046': 'Pathologic Function',
    'T047': 'Disease or Syndrome',
    'T048': 'Mental or Behavioral Dysfunction',
    'T049': 'Cell or Molecular Dysfunction',
    'T050': 'Experimental Model of Disease',
    'T051': 'Event',
    'T052': 'Activity',
    'T053': 'Behavior',
    'T054': 'Social Behavior',
    'T055': 'Individual Behavior',
    'T056': 'Daily or Recreational Activity',
    'T057': 'Occupational Activity',
    'T058': 'Health Care Activity',
    'T059': 'Laboratory Procedure',
    'T060': 'Diagnostic Procedure',
    'T061': 'Therapeutic or Preventive Procedure',
    'T062': 'Research Activity',
    'T063': 'Molecular Biology Research Technique',
    'T064': 'Governmental or Regulatory Activity',
    'T065': 'Educational Activity',
    'T066': 'Machine Activity',
    'T067': 'Phenomenon or Process',
    'T068': 'Human-caused Phenomenon or Process',
    'T069': 'Natural Phenomenon or Process',
    'T070': 'Human-caused Phenomenon or Process',
    'T071': 'Entity',
    'T072': 'Physical Object',
    'T073': 'Manufactured Object',
    'T074': 'Medical Device',
    'T075': 'Research Device',
    'T077': 'Conceptual Entity',
    'T078': 'Idea or Concept',
    'T079': 'Temporal Concept',
    'T080': 'Qualitative Concept',
    'T081': 'Quantitative Concept',
    'T082': 'Spatial Concept',
    'T083': 'Functional Concept',
    'T084': 'Classification',
    'T085': 'Regulation or Law',
    'T086': 'Group',
    'T087': 'Professional Group',
    'T088': 'Population Group',
    'T089': 'Family Group',
    'T090': 'Patient or Disabled Group',
    'T091': 'Age Group',
    'T092': 'Population Group',
    'T093': 'Self-help or Relief Organization',
    'T094': 'Organization',
    'T095': 'Professional or Occupational Group',
    'T096': 'Educational Institution',
    'T097': 'Governmental or Regulatory Organization',
    'T098': 'Research Organization',
    'T099': 'Healthcare Related Organization',
    'T100': 'Laboratory',
    'T101': 'School',
    'T102': 'Group Attribute',
    'T103': 'Organism Attribute',
    'T104': 'Clinical Attribute',
    'T109': 'Organic Chemical',
    'T110': 'Chemical',
    'T111': 'Element, Ion, or Isotope',
    'T114': 'Nucleic Acid, Nucleoside, or Nucleotide',
    'T116': 'Amino Acid, Peptide, or Protein',
    'T120': 'Chemical Viewed Structurally',
    'T121': 'Pharmacologic Substance',
    'T122': 'Biomedical or Dental Material',
    'T123': 'Biologically Active Substance',
    'T124': 'Neoplastic Process',
    'T125': 'Hormone',
    'T126': 'Enzyme',
    'T127': 'Vitamin',
    'T129': 'Immunologic Factor',
    'T130': 'Indicator, Reagent, or Diagnostic Aid',
    'T131': 'Hazardous or Poisonous Substance',
    'T167': 'Substance',
    'T168': 'Food',
    'T169': 'Receptor',
    'T170': 'Carbohydrate',
    'T171': 'Steroid',
    'T184': 'Sign or Symptom',
    'T185': 'Classification',
    'T190': 'Anatomical Abnormality',
    'T191': 'Neoplastic Process',
} 